### ISSUE TITLE
Cannot create booking availability: Return value of App\BookingEvent::newAvailability() must be an instance of Rinvex\Bookings\Models\BookingAvailability, instance of Rinvex\Bookings\Models\BookingRate returned

### ISSUE THREAD

**Issue by Peter2962** [rinvex/laravel-bookings#12]
Hi,

I am trying to create  booking availability following the example given in the docs. But i keep getting this error: 
**"Type error: Return value of App\BookingEvent::newAvailability() must be an instance of Rinvex\Bookings\Models\BookingAvailability, instance of Rinvex\Bookings\Models\BookingRate returned"**

Here is my small bit of code below:
```
$event = BookingEvent::find(1);
$event->newAvailability('thu', '09:00 am', '05:00 pm', 10.5);
```
Here is my BookingEvent class:
```
<?php

namespace App;

use Rinvex\Bookings\Traits\Bookable;
use Illuminate\Database\Eloquent\Model;

class BookingEvent extends Model
{
	use Bookable;

	/**
	* @param 	$request Illuminate\Http\Request
	* @access 	public
	* @return 	String
	*/
	public function getBookings(Request $request)
	{
		
	}
}
```

Thank you.

**Comment by Omranic** [comment]
Please use the *develop* branch as it's the most updated for now, and this issue should be fixed. Feel free to open this issue or a new one if you need further assistance.

**Comment by Peter2962** [comment]
Okay thank you. I will reopen issue if any need be.
