### ISSUE TITLE
Cant Pull Repo

### ISSUE THREAD

**Issue by lewisthompson93** [rinvex/laravel-bookings#13]
Hi, 
I cant use this repo in my project, it seems to have something to do with the `dev-develop` bits in the required section of the `composer.json`

Please see the error i received below in my terminal:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for rinvex/bookings ^0.0.2 -> satisfiable by rinvex/bookings[v0.0.2].
    - rinvex/bookings v0.0.2 requires rinvex/cacheable dev-develop -> satisfiable by rinvex/cacheable[dev-develop] but these conflict with your requirements or minimum-stability.


Installation failed, deleting ./composer.json.
```

Any help would be greatly received, many thanks.

**Comment by Omranic** [comment]
Hello dear @lewisthompsongeonet, You need to change your project's [minimum stability](https://getcomposer.org/doc/04-schema.md#minimum-stability) to `dev`, Regards
