### ISSUE TITLE
Laravel 5.7+ support

### ISSUE THREAD

**Issue by shahzad-sarwar** [rinvex/laravel-bookings#19]
Hi, I am wondering if this package can be installed in Laravel 5.7*.
I was trying to install it, but it's not satisfiable on Laravel 5.7.

**Comment by haringsrob** [comment]
I am using with 5.7 without any issues. Are you still having issues with the latest versions?

**Comment by dambridge** [comment]
When installing on 5.7:
`
Problem 1
    - Conclusion: don't install spatie/laravel-translatable 2.2.1
    - Installation request for rinvex/laravel-bookings ^1.0 -> satisfiable by rinvex/laravel-bookings[v1.0.0].
    - Conclusion: remove laravel/framework v5.7.15
    - Installation request for spatie/laravel-translatable (locked at 3.1.0) -> satisfiable by spatie/laravel-translatable[3.1.0].
    - Conclusion: don't install laravel/framework v5.7.15
`

**Comment by dambridge** [comment]
Looks like it's the dependencies in composer.json. May need to fork and update.

**Comment by Omranic** [comment]
This package is currently supporting Laravel v5.7+ enjoy 🙂
