### ISSUE TITLE
Date based rates

### ISSUE THREAD

**Issue by sandervanhooft** [rinvex/laravel-bookings#2]
Thanks for sharing this package!

I looked through the code, but couldn't find an answer... Is there a way to set booking rates based on other things than quantity of a specific unit?

I.e. to have a different rate for a weekend / midweek etc.?

**Comment by Omranic** [comment]
Absolutely, you can set date based rates of course, but that's called availability prices. Through the bookqble resource itself, you can optionally either flat rate, or custom rates per day and even hours 😉 Let me know if you can't figure it out 👌

**Comment by sandervanhooft** [comment]
That's nice(!), but I'm not sure yet it entirely covers my use case.

Say you have a room (resource) which has an availability of 24/7. It has a weekend price (+20% per day), a midweek price (+0% per day), and a high-season price (+30% per day).

If I book from Wednesday to next Thursday in the high-season, what should be charged? Can this package handle this use case (with a little configuration obviously :) )?

Perhaps a better solution for me would be to use the bookable package to book and calculate a basic fee, and then discount / top up in the actual order model.

Suggestions would be welcome!

**Comment by Omranic** [comment]
Well, as far as I understand your use case, this package totally supports it. The point here is that this package doesn't do the calculation for you, it has nothing to do with doing the math or the payment, so it's intentionally left to the developer implementation. So shortly, you can set your rates as you wish, as per your explanation, and in your ordering process, make sure to take into consideration these rates & availability prices. 

Please feel free to open this issue, or a new one if you've further questions 🙂
