### ISSUE TITLE
Class App\Room contains 3 abstract methods and must therefore be declared abstract

### ISSUE THREAD

**Issue by shahzad-sarwar** [rinvex/laravel-bookings#20]
I am getting the following error. Any help would be appreciated.

Class App\Room contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (App\Room::getBookingModel, App\Room::getRateModel, App\Room::getAvailabilityModel)

**Comment by lbhurtado** [comment]
Same here. Code you provide us a sample project or a snippet of code re: Bookable and HasBookings traits? Thanks.

**Comment by PSalador** [comment]
I get the same error in Bookable traits.

**Comment by haringsrob** [comment]
I think the documentation needs to be adapted.

I did the following to make it work:

1. Created an availability model:
```php
class Availability extends BookableAvailability
{
    protected $table = 'bookable_availabilities';
}
```

2. Created a booking model:
```php
class Booking extends BookableBooking
{
    protected $table = 'bookable_bookings';
}
```

3. Created a rate model:
```php
class Rate extends BookableRate
{
    protected $table = 'bookable_rates';
}
```

Then on my bookable model:

```php
    use Bookable;

    /**
     * Get the booking model name.
     *
     * @return string
     */
    public static function getBookingModel(): string
    {
        return Booking::class;
    }

    /**
     * Get the rate model name.
     *
     * @return string
     */
    public static function getRateModel(): string
    {
        return Rate::class;
    }

    /**
     * Get the availability model name.
     *
     * @return string
     */
    public static function getAvailabilityModel(): string
    {
        return Availability::class;
    }
```

And for the use HasBookings:

```php
    use HasBookings;

    /**
     * Get the booking model name.
     *
     * @return string
     */
    public static function getBookingModel(): string
    {
        return Booking::class;
    }
```

There are some validation errors when creating the objects, but that seems out of scope for this issue. But just as a reference I did the following override on the booking class:

```php
    protected static function boot()
    {
        parent::bootTraits();

        static::validating(function (self $bookableAvailability) {
            if ($bookableAvailability->price === null) {
                $data = $bookableAvailability->calculatePrice(
                    $bookableAvailability->bookable,
                    $bookableAvailability->starts_at,
                    $bookableAvailability->ends_at
                );
                $bookableAvailability->currency = 'EUR';
                $bookableAvailability->quantity = 1;
                $bookableAvailability->formula = [$data['unit']];
                $bookableAvailability->price = $data['total_price'];
                $bookableAvailability->total_paid = 0;
                return;
            }
        });
    }
```

The original boot method seems to have an issue that will make it fail "always". Have not investigated it further.

**Comment by tanthammar** [comment]
@haringsrob Thank you for sharing your solution. It got me on the way to resolve this error. But the boot() function needs some changes otherwise the price will always be 0.

## 1. Wrong documentation:

> Rinvex Bookings assumes that your resource model has at least three fields, `price` as a decimal field, and lastly unit as a string field which accepts one of (minute, hour, day, month) respectively.

The original `calculatePrice()` method **ignores** the `price` field. It looks for `unit_cost` and `base_cost`
```js
$totalPrice = $bookable->base_cost + ($bookable->unit_cost * $totalUnits * $quantity);
```
## 2. Missing documentation for unit field
The docs says the `unit` field accepts `minute, hour, day, month`, but it also accepts `use`, if you always want 1 unit (avoiding date calculation) on your booking. 
```js
//calculatePrice()
case 'use':
    $totalUnits = 1;
    $totalPrice = $bookable->base_cost + ($bookable->unit_cost * $totalUnits * $quantity);
    break;
```
## 3. Bug in Rinvex BookableBooking boot()
The first row expects `price`, `formula` and `currency` params, but if the `price` is 0 it receives an array from `calculate_price()`, never price nor currency.
Thus this code will always error on a new booking.
```js
    protected static function boot()
    {
        parent::boot();

        static::validating(function (self $bookableAvailability) {
            [$price, $formula, $currency] = is_null($bookableAvailability->price) ? $bookableAvailability->calculatePrice($bookableAvailability->bookable, $bookableAvailability->starts_at, $bookableAvailability->ends_at) : [$bookableAvailability->price, $bookableAvailability->formula, $bookableAvailability->currency];

            $bookableAvailability->currency = $currency;
            $bookableAvailability->formula = $formula;
            $bookableAvailability->price = $price;
        });
    }
```
This is what is returned from `calculate_price()`
```js
return [
            'base_cost' => $bookable->base_cost,
            'unit_cost' => $bookable->unit_cost,
            'unit' => $bookable->unit,
            'currency' => $bookable->currency,
            'total_units' => $totalUnits,
            'total_price' => $totalPrice,
];
```
## Solution
Follow the instructions posted by @haringsrob with some modifications to the `boot()` on your `Booking`model. Please note the `quantity` param. It might need another solution in your application.
```php
<?php

namespace App;

use Rinvex\Bookings\Models\BookableBooking;

class Booking extends BookableBooking
{
    protected $table = 'bookable_bookings';

    protected static function boot()
    {
        parent::bootTraits();

        static::validating(function (self $bookableAvailability) {
            if (!$bookableAvailability->price) {
                $formula = $bookableAvailability->calculatePrice(
                    $bookableAvailability->bookable,
                    $bookableAvailability->starts_at,
                    $bookableAvailability->ends_at
                );
                $price = $formula['total_price'];
                $currency = $formula['currency'];
            } else {
                $price = $bookableAvailability->price;
                $formula = $bookableAvailability->formula;
                $currency = $bookableAvailability->currency;
            }
            $bookableAvailability->currency = $currency;
            $bookableAvailability->formula = $formula;
            $bookableAvailability->price = $price;
            $bookableAvailability->quantity = 1;
            $bookableAvailability->total_paid = 0;
        });
    }
}
```

**Comment by gangrelg** [comment]
Hi guys, I followed every single step provided here and yes it does the trick. I have a question, does somebody knows how to properly add BookableAvailability for the resource. I mean I want to make a room available at certain days and specific times. Thanks!

**Comment by hussien-m** [comment]
Class 'App\Models\ServiceBooking' not found why

**Comment by ghadeerMayya** [comment]
Class 'App\Models\ServiceBooking' not found why

**Comment by Omranic** [comment]
Thank you for your patience. The availability features implementation wasn't completed in the perfect possible way, so I'd expect some edge cases, and possibly odd behavior. I'd be happy to consider any PRs that consolidate this feature. All PRs are welcome 😉 

Added to the readme roadmap
https://github.com/rinvex/laravel-bookings/blob/develop/README.md#roadmap

**Comment by ehs4nm** [comment]
is there a complete doc about this package to read about availability and other traits? how to implement it? any demo?

**Comment by Omranic** [comment]
@ehs4nm currently no, but would be happy to consider any PRs 🙂
