### ISSUE TITLE
I have issues migrating the php artisan rinvex:migrate:bookings

### ISSUE THREAD

**Issue by Maerryham** [rinvex/laravel-bookings#25]
I'm a laravel newbie, please help me out, After using the composer code for install, i ran into issues during the migration. I got this error and I dont know how to go about it

$ php artisan rinvex:migrate:bookings
Migrate Rinvex Bookings Tables.
Migrating: 2017_06_27_143745_create_bookable_bookings_table

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access
 violation: 1064 You have an error in your SQL syntax; check the manual that cor
responds to your MariaDB server version for the right syntax to use near 'json n
ull, `notes` text null, `created_at` timestamp null, `updated_at` timestam' at l
ine 1 (SQL: create table `bookable_bookings` (`id` int unsigned not null auto_in
crement primary key, `bookable_type` varchar(191) not null, `bookable_id` bigint
 unsigned not null, `customer_type` varchar(191) not null, `customer_id` bigint
unsigned not null, `starts_at` datetime null, `ends_at` datetime null, `canceled
_at` datetime null, `timezone` varchar(191) null, `price` decimal(8, 2) not null
 default '0.00', `quantity` int unsigned not null, `total_paid` decimal(8, 2) no
t null default '0.00', `currency` varchar(3) not null, `formula` text null, `opt
ions` json null, `notes` text null, `created_at` timestamp null, `updated_at` ti
mestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate
 'utf8mb4_unicode_ci')

  at C:\Users\USER\aquapool\vendor\laravel\framework\src\Illuminate\Database\Con
nection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll
 format the error
    661|         // message to include the bindings with SQL, which will make th
is exception a
    662|         // lot more helpful to the developer instead of just the databa
se's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 Yo
u have an error in your SQL syntax; check the manual that corresponds to your Ma
riaDB server version for the right syntax to use near 'json null, `notes` text n
ull, `created_at` timestamp null, `updated_at` timestam' at line 1")
      C:\Users\USER\aquapool\vendor\laravel\framework\src\Illuminate\Database\Co
nnection.php:452

  2   PDO::prepare("create table `bookable_bookings` (`id` int unsigned not null
 auto_increment primary key, `bookable_type` varchar(191) not null, `bookable_id
` bigint unsigned not null, `customer_type` varchar(191) not null, `customer_id`
 bigint unsigned not null, `starts_at` datetime null, `ends_at` datetime null, `
canceled_at` datetime null, `timezone` varchar(191) null, `price` decimal(8, 2)
not null default '0.00', `quantity` int unsigned not null, `total_paid` decimal(
8, 2) not null default '0.00', `currency` varchar(3) not null, `formula` text nu
ll, `options` json null, `notes` text null, `created_at` timestamp null, `update
d_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4
 collate 'utf8mb4_unicode_ci'")
      C:\Users\USER\aquapool\vendor\laravel\framework\src\Illuminate\Database\Co
nnection.php:452

  Please use the argument -v to see more details.

**Comment by Omranic** [comment]
You can now override migrations!
All packages have been updated to include this feature, check latest releases 😉 enjoy!
