### ISSUE TITLE
Class rinvex.bookings.bookable-booking does not exist

### ISSUE THREAD

**Issue by alfarioekaputra** [rinvex/laravel-bookings#27]
Hi,

I am trying to create booking availability following the example given in the docs. But i keep getting this error:

i use laravel 5.8

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/650641/54254598-e3b90b00-4586-11e9-81e3-28deaa5041c3.png">

**Comment by easterneas** [comment]
I second this, though I've updated my existing project from 5.7 to 5.8. Followed the instructions in README.md, but things went south.

![image](https://user-images.githubusercontent.com/31128200/56892543-2ccb0d00-6aaa-11e9-858e-859806666411.png)

The partial trace (in which I called the `app()` function) is logged above

**Comment by boghy933** [comment]
Anyone has find a way to solve this problem? Thank you

**Comment by alhad15** [comment]
I was able to make it work by replacing  "rinvex.bookings.bookable-booking" with my model used for Booking  app('App\Models\Booking').

**Comment by alfarioekaputra** [comment]
thanks @alhad15

**Comment by Omranic** [comment]
Sorry about that, the docs were outdated. Now it's fixed (but still missing few features) 93c45b694d7b2799ecdf539c0b24900b743e1751
