### ISSUE TITLE
Unable to create BookableRate, Watson: the given data was invalid

### ISSUE THREAD

**Issue by tanthammar** [rinvex/laravel-bookings#29]
"rinvex/laravel-bookings": "^2.1"
"laravel/framework": "5.8.*"

Error: Watson/Validating/ValidationException with message 'The given data was invalid.'

php artisan tinker
```js
$room = \App\Room::find(1);
$room->newRate('15', '^', 2, $room);
```

App\Room
```php
<?php

namespace App;

use Rinvex\Bookings\Traits\Bookable;
use Illuminate\Database\Eloquent\Model;
use App\BookableRate;

class Room extends Model
{
    use Bookable;

public function newRate($percent, $operator, $unit, $bookable): BookableRate
    {
        $rate = new BookableRate;
        $rate->make(['percentage' => $percent, 'operator' => $operator, 'amount' => $unit])
            ->bookable()->associate($bookable)
            ->save();
        return $rate;
    }
}
```

App\BookableRate
```php
<?php

namespace App;

use Rinvex\Bookings\Models\BookableRate as RinvexBookableRate;

class BookableRate extends RinvexBookableRate
{
    protected $table = 'bookable_rates';

}
```

**Comment by jeanlinux** [comment]
@tanthammar I have the Exception when I try to create a new booking ... Have you found any solution to this issue, it appears to be a validation issue but cant tell what exactly is going on behind the scenes

**Comment by jeanlinux** [comment]
@tanthammar If you are still facing this issue, checkout this related issue for a solution https://github.com/rinvex/laravel-bookings/issues/34.

basically, you have to add required properties that are missing on the newBooking() method, override this method in your model and provide the extra required properties with their values and its solved

**Comment by jorndullemans** [comment]
I still got the same error.

**Comment by Omranic** [comment]
Thank you for highlighting that issue. I added a task to the roadmap to improve the documentation and add a workable example to make it clear. https://github.com/rinvex/laravel-bookings/blob/develop/README.md#roadmap
