### ISSUE TITLE
Booking not validating availability

### ISSUE THREAD

**Issue by harredon01** [rinvex/laravel-bookings#30]
I was looking through the package and I dont understand how the availability of the bookable objects are validated. Do you have an example of how we can validate that if a model has an availability object created, the booking dates must be between the availability object range in order to be created?
I also dont understand why the from and to columns in the availability model are strings and not dates

how should we validate that bookings are between the availability objects when the date fields are not dates?
`$serviceBooking = new \App\Models\Availability();`
`$serviceBooking->make(['range' => 'monday', 'from' => '08:00 am', 'to' => '12:30 pm', 'is_bookable' => true])
                ->bookable()->associate($merchant)
                ->save();`
`$merchant->newBooking($user, '2019-07-01 12:44:12', '2019-07-01 14:30:11');`

This booking should not be created because the date range is not with the available date range. However both objects are created and stored.
thank you

**Comment by Omranic** [comment]
Thank you for your patience. The availability features implementation wasn't completed in the perfect possible way, so I'd expect some edge cases, and possibly odd behavior. I'd bee happy to consider any PRs that consolidate this feature. All PRs are welcome 😉 

Added to the readme roadmap
https://github.com/rinvex/laravel-bookings/blob/develop/README.md#roadmap
