### ISSUE TITLE
Undefined index 0 in BookableBooking boot method

### ISSUE THREAD

**Issue by ghost** [rinvex/laravel-bookings#31]
hi, just getting started with this package but i'm facing the error in the title.
It seems that in the boot method

```
protected static function boot()
    {
        parent::boot();
        static::validating(function (self $bookableAvailability) {
            [$price, $formula, $currency] = is_null($bookableAvailability->price)
                ? $bookableAvailability->calculatePrice($bookableAvailability->bookable, $bookableAvailability->starts_at, $bookableAvailability->ends_at) : [$bookableAvailability->price, $bookableAvailability->formula, $bookableAvailability->currency];
            $bookableAvailability->currency = $currency;
            $bookableAvailability->formula = $formula;
            $bookableAvailability->price = $price;
        });
    }
```

The calculatePrice function is returning an associative array, while php is expecting an indexed array when assigning the result of the calculatePrice function

`[$price, $formula, $currency] =  [...]$bookableAvailability->calculatePrice([...])`

.. Am i missing something ?

**Comment by martinnaughton** [comment]
this is whe n the price is null.

**Comment by ghost** [comment]
Already a very old issue, but still many thanks for the answer as it might help someone in the future.

**Comment by martinnaughton** [comment]
it is still an issue even though the code is refactored. Currently working out what the issue is. calculatePrice is still returning undefined 0.

**Comment by ghost** [comment]
In my project I had to override the `validating` function of the `BookableBooking` Model like below.
Maybe it helps to identify the root cause....

```
class MyBooking extends BookableBooking implements Buyable, Searchable
{

    /**
     * Needed cause of a bug https://github.com/rinvex/laravel-bookings/issues/31
     */
    protected static function boot()
    {
        parent::bootTraits();
        Model::boot();

        static::validating(function (self $bookableAvailability) {
            if (!$bookableAvailability->price) {
                $formula = $bookableAvailability->calculatePrice(
                    $bookableAvailability->bookable,
                    $bookableAvailability->starts_at,
                    $bookableAvailability->ends_at
                );
                $price = $formula['total_price'];
                $currency = $formula['currency'];
                $quantity = $formula['total_units'];
            } else {
                $price = $bookableAvailability->price;
                $formula = $bookableAvailability->formula;
                $currency = $bookableAvailability->currency;
                $quantity = $bookableAvailability->quantity;
            }
            $bookableAvailability->currency = $currency;
            $bookableAvailability->formula = $formula;
            $bookableAvailability->price = $price;
            $bookableAvailability->quantity = $quantity;
            $bookableAvailability->total_paid = 0;
        });
    }

   ...
```

**Comment by martinnaughton** [comment]
the original issue that is still there is the way it has been programmed to use array deconstructure

```Before 7.1 it was only worked on numerical arrays and assumes the numerical indices start at 0. ```

https://www.php.net/manual/en/function.list.php
```7.1.0 | It is now possible to specify keys in list(). This enables destructuring of arrays with non-integer or non-sequential keys.```

An example here this does not work because they are non integer indices on the right side you are trying to deconstruct. The right side is a named keys.
` [$price, $formula, $currency] = ["price" => 2, "formula" => 2];`

 To deconstruct named keys you need to have a key on the left hand side. This works now when decontructing
`['price' => $price, 'formula' => $formula] = ["formula" => 2, "price" => 10];`


What is returned from calculatePrice is a named list so it will never work with array deconstructing  [$price, $formula, $currency] :
```
return [
            'base_cost' => $bookable->base_cost,
            'unit_cost' => $bookable->unit_cost,
            'unit' => $bookable->unit,
            'currency' => $bookable->currency,
            'total_units' => $totalUnits,
            'total_price' => $totalPrice,
        ];
```

**Comment by martinnaughton** [comment]
can you open again because this is still an issue for everyone?

**Comment by Omranic** [comment]
Thank you for your patience, I commented that part of the code until the availability features are well implemented as it's currently incomplete https://github.com/rinvex/laravel-bookings/commit/0b49edb3e66dcfd47bb166fc18d2a0e04ee856bd
