### ISSUE TITLE
Missing functionality that is present in the documentation.

### ISSUE THREAD

**Issue by jonagoldman** [rinvex/laravel-bookings#32]
I see some critical methods and services that are present in the documentation but in reality missing from the code base. For example the `newPrice()` is not available anywhere. I am missing something? Was the documentation written before the actual code?

**Comment by martinnaughton** [comment]
Also seen that issue. Maybe the code is not pushed. the newPrice() method should be part of bookable trait but not at the moment.

https://github.com/rinvex/laravel-bookings/blob/63c1022fc87eb37426e888e383dfbe249c1d85f1/src/Traits/Bookable.php

**Comment by martinnaughton** [comment]
the method was introduced in this commit on  Oct 17, 2017
https://github.com/rinvex/laravel-bookings/blob/714b372637da1fba6beb43a96f202d933abdf37f/src/Traits/Bookable.php

It was removed here on Mar 28, 2018
https://github.com/rinvex/laravel-bookings/commit/768b3995e147bdb7b0413e3b59c4319973e57430#diff-9a01e33ec955aa88e56fce3a3fcdde8a

I think just the documentation needs to be updated.

**Comment by martinnaughton** [comment]
I think the library wants to be more based on availability then price looking at the changes.

**Comment by Omranic** [comment]
Thank you for your patience, yes the documentation is outdated (will fix that!), however that method `newPrice` is no longer used in the current codebase. 

As @martinnaughton mentioned, the package has been re-written, and prices are now based on availability:
> I think the library wants to be more based on availability then price looking at the changes.

All PRs to improve the code, or enhance the documentation are welcome 😉
