### ISSUE TITLE
Can not create newBooking() and validation does not throw an error

### ISSUE THREAD

**Issue by martinnaughton** [rinvex/laravel-bookings#34]
Laravel: 6.4
laravel-bookings: v3.0.1

In this code below will not work
[Bookable trait](https://github.com/rinvex/laravel-bookings/blob/master/src/Traits/Bookable.php)
```
public function newBooking(Model $customer, string $startsAt, string $endsAt): BookableBooking
    {
        return $this->bookings()->create([
            'bookable_id' => static::getKey(),
            'bookable_type' => static::getMorphClass(),
            'customer_id' => $customer->getKey(),
            'customer_type' => $customer->getMorphClass(),
            'starts_at' => (new Carbon($startsAt))->toDateTimeString(),
            'ends_at' => (new Carbon($endsAt))->toDateTimeString(),
        ]);
    }
```

because it is missing 4 required properties. Here is the sample ones it needs
```
price' => 1,
 'quantity' => 1,
 'total_paid' => 1,
 'currency' => 'EUR',
```

They are set to required Bookablebookings and there is a validation trait that should warn the user that  the information is not provided so show and error.
[Bookablebookings](https://github.com/rinvex/laravel-bookings/blob/master/src/Models/BookableBooking.php)
```
price' => 'required|numeric',
 'quantity' => 'required|integer',
 'total_paid' => 'required|numeric',
 'currency' => 'required|alpha|size:3',
```

Only issue though is it does not throw an error that the information is not provided even though this variable is set to true below. If it set it to false i find out that i am missing those 4 properties. 
[Bookablebookings](https://github.com/rinvex/laravel-bookings/blob/master/src/Models/BookableBooking.php)
```
/**
     * Whether the model should throw a
     * ValidationException if it fails validation.
     *
     * @var bool
     */
    protected $throwValidationExceptions = true;
```

Once the 4 properties are provided then the booking is created.

**Comment by Omranic** [comment]
Thank you for highlighting that issue. I added a task to the roadmap to improve the documentation and add a workable example to make it clear. https://github.com/rinvex/laravel-bookings/blob/develop/README.md#roadmap
