### ISSUE TITLE
Can`t publish

### ISSUE THREAD

**Issue by AlexanderKostrov** [rinvex/laravel-bookings#36]
I try:
php artisan rinvex:publish:bookings

But error:
Unable to locate publishable resources.

How to fix it?

**Comment by foodlz** [comment]
same here. Laravel Framework 6.18.8

php artisan rinvex:publish:bookings
**********************************************
*     Publish Rinvex Bookings Resources.     *
**********************************************

Unable to locate publishable resources.
Publishing complete.
Unable to locate publishable resources.
Publishing complete.

**Comment by foodlz** [comment]
change the APP_ENV to production

**Comment by AlexanderKostrov** [comment]
@foodlz Thank you, very much! It`s work !
