### ISSUE TITLE
Does this package support Laravel 7

### ISSUE THREAD

**Issue by jigsawsoul** [rinvex/laravel-bookings#39]
Hi, 

I am confused as to what version of Laravel this package supports as it does not seem to be mentioned within the README file. When installing on 7.18.0 I get the following error:

![image](https://user-images.githubusercontent.com/14300454/86406444-05259500-bcab-11ea-94ef-6df8674fd1e6.png)

Thank you in advance.

**Comment by Omranic** [comment]
Yes, Laravel v7.x is supported in recent versions of this package v4.x but also PHP v7.4 is required :)
