### ISSUE TITLE
Laravel 7.x support

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [rinvex/laravel-bookings#40]
Hi,
Will this package be updated for Laravel 7.x support?
Best regards

**Comment by ShapesGraphicStudio** [comment]
Sorry for posting too fast, I was requiring an older package version.
Install works fine with:
`"rinvex/laravel-bookings": "^4.0"`
if also using:
`"php": "^7.4"`

**Comment by Omranic** [comment]
All packages supports Laravel v7.x :)
Make sure you're using v4.x of the package, and yes it requires PHP v7.4
