### ISSUE TITLE
Migrations override

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [rinvex/laravel-bookings#41]
Hi,
I tried to override migrations by publishing them: 
`php artisan rinvex:publish:bookings`

The files were copied to database/migrations/rinvex/laravel-bookings where I was able to edit them.

But
`php artisan migrate `
keeps looking for the original files in vendor/rinvex/...

Could you please tell me what I missed here?

Best regards

**Comment by Omranic** [comment]
You need to disable the [`autoload_migrations`](https://github.com/rinvex/laravel-bookings/blob/master/config/config.php#L8) config option, that's it 🙂

**Comment by ShapesGraphicStudio** [comment]
Nice one indeed, thanks..
