### ISSUE TITLE
Compatible with Laravel 7 

### ISSUE THREAD

**Issue by luiscolmenares** [rinvex/laravel-bookings#42]
Hi, is this resource compatible with Laravel 7?

`mylaptop$compose require rinvex/laravel-bookings
    1/3:	http://repo.packagist.org/p/provider-latest$d85582671f6aef8a868923ab273c8ad3b9f80d8e051472408d069791b6dd49ce.json
    2/3:	http://repo.packagist.org/p/provider-2020-04$6e73c81f2134310798c60323af2b1d1b7124edc5849c469d5d7117fd6c509105.json
    3/3:	http://repo.packagist.org/p/provider-2019$df5759627fed52d18a0a28d474af6fc9139baa9ae79b27b5fe8ea6ddcef8eda1.json
    Finished: success: 3, skipped: 0, failure: 0, total: 3
Using version ^3.0 for rinvex/laravel-bookings
./composer.json has been updated
    1/3:	http://repo.packagist.org/p/provider-latest$d85582671f6aef8a868923ab273c8ad3b9f80d8e051472408d069791b6dd49ce.json
    2/3:	http://repo.packagist.org/p/provider-2020-04$6e73c81f2134310798c60323af2b1d1b7124edc5849c469d5d7117fd6c509105.json
    3/3:	http://repo.packagist.org/p/provider-2019$df5759627fed52d18a0a28d474af6fc9139baa9ae79b27b5fe8ea6ddcef8eda1.json
    Finished: success: 3, skipped: 0, failure: 0, total: 3
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v7.3.0
    - Conclusion: don't install laravel/framework v7.3.0
    - rinvex/laravel-bookings v3.0.0 requires illuminate/support ^6.0.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.26, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-bookings v3.0.1 requires illuminate/support ^6.0.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.26, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-bookings v3.0.2 requires illuminate/support ^6.0.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.26, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-bookings v3.0.3 requires illuminate/support ^6.0.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.26, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - Can only install one of: laravel/framework[6.x-dev, v7.3.0].
    - don't install illuminate/support 6.x-dev|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.0.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.0.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.0.2|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.0.3|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.0.4|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.1.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.10.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.11.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.12.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.13.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.13.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.14.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.15.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.15.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.16.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.17.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.17.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.10|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.11|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.12|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.13|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.14|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.15|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.16|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.17|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.18|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.19|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.2|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.20|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.21|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.22|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.23|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.24|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.25|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.26|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.3|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.4|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.5|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.6|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.7|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.8|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.9|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.2.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.3.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.4.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.5.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.5.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.5.2|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.6.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.6.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.6.2|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.7.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.8.0|don't install laravel/framework v7.3.0
    - Installation request for laravel/framework (locked at v7.3.0, required as ^7.0) -> satisfiable by laravel/framework[v7.3.0].
    - Installation request for rinvex/laravel-bookings ^3.0 -> satisfiable by rinvex/laravel-bookings[v3.0.0, v3.0.1, v3.0.2, v3.0.3].

Installation failed, reverting ./composer.json to its original content.
mylaptop$ COMPOSER_MEMORY_LIMIT=-1 composer require rinvex/laravel-bookings
    1/3:	http://repo.packagist.org/p/provider-latest$d85582671f6aef8a868923ab273c8ad3b9f80d8e051472408d069791b6dd49ce.json
    2/3:	http://repo.packagist.org/p/provider-2019$df5759627fed52d18a0a28d474af6fc9139baa9ae79b27b5fe8ea6ddcef8eda1.json
    3/3:	http://repo.packagist.org/p/provider-2020-04$6e73c81f2134310798c60323af2b1d1b7124edc5849c469d5d7117fd6c509105.json
    Finished: success: 3, skipped: 0, failure: 0, total: 3
Using version ^3.0 for rinvex/laravel-bookings
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v7.3.0
    - Conclusion: don't install laravel/framework v7.3.0
    - rinvex/laravel-bookings v3.0.0 requires illuminate/support ^6.0.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.26, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-bookings v3.0.1 requires illuminate/support ^6.0.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.26, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-bookings v3.0.2 requires illuminate/support ^6.0.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.26, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-bookings v3.0.3 requires illuminate/support ^6.0.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.26, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - Can only install one of: laravel/framework[6.x-dev, v7.3.0].
    - don't install illuminate/support 6.x-dev|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.0.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.0.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.0.2|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.0.3|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.0.4|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.1.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.10.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.11.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.12.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.13.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.13.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.14.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.15.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.15.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.16.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.17.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.17.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.10|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.11|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.12|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.13|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.14|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.15|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.16|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.17|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.18|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.19|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.2|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.20|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.21|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.22|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.23|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.24|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.25|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.26|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.3|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.4|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.5|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.6|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.7|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.8|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.18.9|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.2.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.3.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.4.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.5.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.5.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.5.2|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.6.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.6.1|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.6.2|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.7.0|don't install laravel/framework v7.3.0
    - don't install illuminate/support v6.8.0|don't install laravel/framework v7.3.0
    - Installation request for laravel/framework (locked at v7.3.0, required as ^7.0) -> satisfiable by laravel/framework[v7.3.0].
    - Installation request for rinvex/laravel-bookings ^3.0 -> satisfiable by rinvex/laravel-bookings[v3.0.0, v3.0.1, v3.0.2, v3.0.3].`

**Comment by Omranic** [comment]
Laravel v7.x is supported in v4.x of this package, which also requires **PHP v7.4** or up.
