### ISSUE TITLE
How to cancel booking

### ISSUE THREAD

**Issue by tree1891** [rinvex/laravel-bookings#43]
I set canceled_at to now, but it occurs error when saving.
Without any change, saving BookableBooking model occurs error.
It seems 'options' member, It is null, but error is 'The options must be an array'

**Comment by Omranic** [comment]
Thank you for your patience. This feature currently not implemented. I'd be happy to consider any PRs that consolidate this feature. All PRs are welcome 😉 

Added to the readme roadmap
https://github.com/rinvex/laravel-bookings/blob/develop/README.md#roadmap

**Comment by vesper8** [comment]
@Omranic so you have a `canceled_at` field and a bunch of scopes that returned canceled bookings, but no actual way to cancel a booking?

I also tried just doing

```
$booking->canceled_at = now();
$booking->save();
```

And it throws a `422` error `The options must be an array`

**Comment by vesper8** [comment]
For anyone stumbling onto this, this works:

```
$booking->canceled_at = now();
$booking->forceSave();
```
