### ISSUE TITLE
Laravel 8.x support ?

### ISSUE THREAD

**Issue by janczakb** [rinvex/laravel-bookings#46]
Laravel 8.x support

**Comment by joserick** [comment]
Same request.

**Comment by schymon17** [comment]
That will be very useful - Laravel 8

**Comment by joserick** [comment]
Meanwhile could use this fork: **"composer require allcaretravel/laravel-bookings"** for Laravel 8

**Comment by schymon17** [comment]
That doesn't work for me

**Comment by Omranic** [comment]
Hello, thank you for your patience, this is now done! Check latest major release!!

This package now supports Laravel v8, PHP v8, Composer v2, enjoy 🥳

CC @janczakb @joserick @schymon17 @schymon17

**Comment by schymon17** [comment]
Still doesnt work

**Comment by Omranic** [comment]
@schymon17 what doesn't work?! Can you provide more details on your issue please, so we can help..

**Comment by schymon17** [comment]
@Omranic 
<img width="1907" alt="Screenshot 2020-12-30 at 01 02 12" src="https://user-images.githubusercontent.com/6172987/103323475-e413e600-4a3a-11eb-9f57-6ecd8c235397.png">

**Comment by Omranic** [comment]
Why you're using v3 of the package?! Latest version is v5 already. Please make sure to require the correct version, and you have all needed requirements which includes PHP v7.4 or up.
