### ISSUE TITLE
error: Could not open input file: artisan. can't install 

### ISSUE THREAD

**Issue by LincolnTK** [rinvex/laravel-bookings#47]
**stuck at 2nd step of installation:**

_2. Publish resources (migrations and config files):

php artisan rinvex:publish:bookings_

**im getting this error:**
_Could not open input file: artisan_

**Comment by thomasmoors** [comment]
[artisan ](https://github.com/laravel/laravel/blob/8.x/artisan) is part of the Laravel framework. This package is not standalone.

**Comment by Omranic** [comment]
Hello @LincolnTK please follow the installation instructions here https://github.com/rinvex/laravel-bookings#installation
