### ISSUE TITLE
Wrong config param

### ISSUE THREAD

**Issue by vrenda** [rinvex/laravel-bookings#6]
https://github.com/rinvex/bookable/blob/b67e8c47f5a5876f1904c3d32200bf1345478eb6/database/migrations/2017_06_27_113745_create_bookings_table.php#L50

I think need change with
`Schema::dropIfExists(config('rinvex.bookable.tables.bookings'));`

Regards

**Comment by Omranic** [comment]
Fixed 4aa1b5a57778b4330ef7ddeccf20194970c17ba3, thank you @vrenda for the report 👍
