### ISSUE TITLE
Is there any known front-end that makes use of this library?

### ISSUE THREAD

**Issue by vesper8** [rinvex/laravel-bookings#61]
Just curious if anyone has spotted, or open-sourced, a UI or front-end solution that works with this package?

**Comment by Omranic** [comment]
We used to have something in the past, but it wasn't complete, maybe you can check it as a starting point. Please note that the other UI package is currently archived, so you may need to fork and do some update on your own: https://github.com/rinvex/cortex-bookings hope it helps!
