### ISSUE TITLE
Dead or alive

### ISSUE THREAD

**Issue by rabol** [rinvex/laravel-bookings#62]
Hi

Is this package dead or alive ?

If alive, when will a workable example be available ?

**Comment by Omranic** [comment]
Hey @rabol, thank you for your patience. I'd be happy to consider any PRs to improve the documentation, and add a workable example. All PRs are welcome 😉  Checkout the roadmap which is calling for contributors to improve the package code & docs 👍  https://github.com/rinvex/laravel-bookings/blob/develop/README.md#roadmap
