### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rshreeharini** [rinvex/laravel-bookings#63]
From the README

## Usage

**Rinvex Bookings** has been specially made for Eloquent and simplicity has been taken very serious as in any other Laravel related aspect. 

### Add bookable functionality to your resource model

To add bookable functionality to your resource model just use the `\Rinvex\Bookings\Traits\Bookable` trait like this:

```php
namespace App\Models;

use Rinvex\Bookings\Traits\Bookable;
use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    use Bookable;
}
```

That's it, you only have to use that trait in your Room model! Now your rooms will be bookable.

### Add bookable functionality to your customer model

To add bookable functionality to your customer model just use the `\Rinvex\Bookings\Traits\HasBookings` trait like this:

```php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Rinvex\Bookings\Traits\HasBookings;

class Customer extends Model
{
    use HasBookings;
}
```

Again, that's all you need to do! Now your Customer model can book resources.

---

That's _not_ all you need to do. It would be helpful if the abstract functions in these traits were documented and explained, i.e. getBookingModel, getRateModel, getAvailabilityModel. Overall the documentation is somewhat sparse.

I am still exploring this package but it seems like it will be a good fit for my application, but the setup was a bit confusing.

**Comment by rshreeharini** [comment]
Also, I had a question about the Bookable model. It's an abstract class, are my "Bookable" items meant to extend this class? This class/model isn't really mentioned that I can see.

**Comment by Omranic** [comment]
Thank you @rshreeharini , yes the docs are currently lacking, and also some of the *Booking Availability* features are incomplete. Any help improving the code or docs are much appreciated, all PRs are welcome.

> Also, I had a question about the Bookable model. It's an abstract class, are my "Bookable" items meant to extend this class? This class/model isn't really mentioned that I can see.

Answering your question: yes, the `Bookable` abstract model is meant to be extended.

**Comment by rshreeharini** [comment]
@Omranic is it meant to be extended by the resource model e.g. Room in your example, or some other class?

**Comment by Omranic** [comment]
Yes, that's right.
