### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kevinwaxi** [rinvex/laravel-bookings#64]
The project sounds cool but too bad, I tried using this in my scenario and I feel like the documentation is lacking something I don't know what exactly but when I just do as per the documentation I face many errors I don't know why tried fixing a few but still more error. if by any chance you could point to me where to read more of this or a working example.

**Comment by Omranic** [comment]
Thank you @kevinwaxi

If you can provide a screenshot of the errors you're getting, maybe we can help you better 🙂 

Feel free to re-open this issue if needed, and explain what's exactly the error you're facing and how to reproduce it.

**Comment by kevinwaxi** [comment]
1 abstract method and must therefore be declared abstract or implement the remaining methods (App\Models\User::getBookingModel) 
![Screenshot_2021-11-24_11-42-59](https://user-images.githubusercontent.com/10962235/143204135-fc861505-d2df-4a31-8897-cd7e5884c5cd.png)

**Comment by Omranic** [comment]
That's very clear. You need to define all [abstract](https://www.php.net/manual/en/language.oop5.abstract.php) methods inside your model class:
https://github.com/rinvex/laravel-bookings/blob/master/src/Traits/Bookable.php#L23-L66
